# $Id: Makefile.src,v 3.1 1999-03-14 10:58:01 virolle Exp $
#
#               Copyright (c) 1998 by IRCAM - Centre Pompidou
#                          All rights reserved.
#
#  For any information regarding this and other IRCAM software, please
#  send email to:
#                            manager@ircam.fr
#
#  src tosdif




SRC = test.c
