site_name: pysdif3
theme:
    name: material
    features:
        # - navigation.tabs
        - navigation.sections

nav:
    - index.md
    - reference.md
    - tools.md
    - classes:
        - classes/SdifFile.md
        - classes/FrameR.md
        - classes/FrameW.md
        - classes/Matrix.md

extra_css:
    - stylesheets/extra.css
      
markdown_extensions:
    - toc:
        toc_depth: 3
    - pymdownx.highlight
    - pymdownx.superfences
    - admonition
    - def_list
    - tables

use_directory_urls: false

repo_url: https://github.com/gesellkammer/pysdif3

